export { Sidebar } from './Sidebar';
export type { ModuleRegistryEntry } from './Sidebar';
export { ShellLayout } from './ShellLayout';
export { DashboardLayout } from './DashboardLayout';
export { TabsLayout } from './TabsLayout';
export { CarouselLayout } from './CarouselLayout';
export { WidgetCard } from './WidgetCard';
export { WidgetErrorBoundary } from './WidgetErrorBoundary';
export { ModuleErrorBoundary } from './ModuleErrorBoundary';
export { ShellRouter } from './ShellRouter';
export type { ShellRouterProps } from './ShellRouter';
export { ConnectionStatusBar } from './ConnectionStatusBar';
export type { ConnectionStatusBarProps } from './ConnectionStatusBar';
